
package com.source;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calc", targetNamespace = "http://source.com")
@XmlSeeAlso({
    ObjectFactory.class
})


public interface Calc {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://source.com")
    @RequestWrapper(localName = "add", targetNamespace = "http://source.com", className = "com.source.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://source.com", className = "com.source.AddResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "http://source.com")
        int a,
        @WebParam(name = "b", targetNamespace = "http://source.com")
        int b);

    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "subReturn", targetNamespace = "http://source.com")
    @RequestWrapper(localName = "sub", targetNamespace = "http://source.com", className = "com.source.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://source.com", className = "com.source.SubResponse")
    public int sub(
        @WebParam(name = "a", targetNamespace = "http://source.com")
        int a,
        @WebParam(name = "b", targetNamespace = "http://source.com")
        int b);

}
