
package com.eds.airlinesoaschema.ping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.eds.airlinesoaschema.airlinepingrq.AirlinePingRQ;
import com.eds.airlinesoaschema.airlinepingrs.AirlinePingRS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PingPortType", targetNamespace = "http://www.eds.com/AirlineSOASchema/Ping/")
@XmlSeeAlso({
    com.eds.airlinesoaschema.airlinepingrq.ObjectFactory.class,
    com.eds.airlinesoaschema.airlinepingrs.ObjectFactory.class,
    org.opentravel.ota._2003._05.commontypes.ObjectFactory.class,
    com.eds.airlinesoaschema.messagerequestbase.ObjectFactory.class,
    com.eds.airlinesoaschema.messageresultbase.ObjectFactory.class,
    com.eds.airlinesoaschema.ping.ObjectFactory.class,
    com.source.ObjectFactory.class,
    org.opentravel.ota._2003._05.simpletypes.ObjectFactory.class,
    com.eds.airlinesoaschema.simpletypes.ObjectFactory.class
})
public interface PingPortType {


    /**
     * 
     * @param airlinePingRQ
     * @return
     *     returns com.eds.airlinesoaschema.airlinepingrs.AirlinePingRS
     */
    @WebMethod(action = "http://www.eds.com/AirlineSOASchema/Ping/ping")
    @WebResult(name = "AirlinePingRS", targetNamespace = "http://www.eds.com/AirlineSOASchema/AirlinePingRS")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.eds.com/AirlineSOASchema/Ping/", className = "com.eds.airlinesoaschema.ping.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.eds.com/AirlineSOASchema/Ping/", className = "com.eds.airlinesoaschema.ping.PingResponse")
    public AirlinePingRS ping(
        @WebParam(name = "AirlinePingRQ", targetNamespace = "http://www.eds.com/AirlineSOASchema/AirlinePingRQ")
        AirlinePingRQ airlinePingRQ);

}
