
package com.hp.airlinesoaschema.modifyseatmap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.hp.airlinesoaschema.airmodifyseatmaprq.HPAirModifySeatMapRQ;
import com.hp.airlinesoaschema.airmodifyseatmaprs.HPAirModifySeatMapRS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModifySeatMapPortType", targetNamespace = "http://www.hp.com/AirlineSOASchema/ModifySeatMap/")
@XmlSeeAlso({
    com.hp.airlinesoaschema.aircommontypes.ObjectFactory.class,
    org.opentravel.ota._2003._05.commontypes.ObjectFactory.class,
    org.opentravel.ota._2003._05.aircommontypes.ObjectFactory.class,
    com.hp.airlinesoaschema.airmodifyseatmaprq.ObjectFactory.class,
    com.hp.airlinesoaschema.airmodifyseatmaprs.ObjectFactory.class,
    com.hp.airlinesoaschema.modifyseatmap.ObjectFactory.class,
    com.source.ObjectFactory.class,
    org.opentravel.ota._2003._05.simpletypes.ObjectFactory.class
})
public interface ModifySeatMapPortType {


    /**
     * 
     * @param hpAirModifySeatMapRQ
     * @return
     *     returns com.hp.airlinesoaschema.airmodifyseatmaprs.HPAirModifySeatMapRS
     */
    @WebMethod(action = "http://www.hp.com/AirlineSOASchema/ModifySeatMap/processModifySeatMap")
    @WebResult(name = "HP_AirModifySeatMapRS", targetNamespace = "http://www.hp.com/AirlineSOASchema/AirModifySeatMapRS")
    @RequestWrapper(localName = "processModifySeatMap", targetNamespace = "http://www.hp.com/AirlineSOASchema/ModifySeatMap/", className = "com.hp.airlinesoaschema.modifyseatmap.ProcessModifySeatMap")
    @ResponseWrapper(localName = "processModifySeatMapResponse", targetNamespace = "http://www.hp.com/AirlineSOASchema/ModifySeatMap/", className = "com.hp.airlinesoaschema.modifyseatmap.ProcessModifySeatMapResponse")
    public HPAirModifySeatMapRS processModifySeatMap(
        @WebParam(name = "HP_AirModifySeatMapRQ", targetNamespace = "http://www.hp.com/AirlineSOASchema/AirModifySeatMapRQ")
        HPAirModifySeatMapRQ hpAirModifySeatMapRQ);

}
