
package com.hp.airlinesoaschema.modifyseatmap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModifySeatMapService", targetNamespace = "http://www.hp.com/AirlineSOASchema/ModifySeatMap/", wsdlLocation = "file:/C:/Users/kaparapr/Desktop/important/WsimportSample/WebContent/wsdl2/wsdl2/Calc.wsdl")
public class ModifySeatMapService
    extends Service
{

    private final static URL MODIFYSEATMAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODIFYSEATMAPSERVICE_EXCEPTION;
    private final static QName MODIFYSEATMAPSERVICE_QNAME = new QName("http://www.hp.com/AirlineSOASchema/ModifySeatMap/", "ModifySeatMapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/kaparapr/Desktop/important/WsimportSample/WebContent/wsdl2/wsdl2/Calc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODIFYSEATMAPSERVICE_WSDL_LOCATION = url;
        MODIFYSEATMAPSERVICE_EXCEPTION = e;
    }

    public ModifySeatMapService() {
        super(__getWsdlLocation(), MODIFYSEATMAPSERVICE_QNAME);
    }

    public ModifySeatMapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODIFYSEATMAPSERVICE_QNAME, features);
    }

    public ModifySeatMapService(URL wsdlLocation) {
        super(wsdlLocation, MODIFYSEATMAPSERVICE_QNAME);
    }

    public ModifySeatMapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODIFYSEATMAPSERVICE_QNAME, features);
    }

    public ModifySeatMapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModifySeatMapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModifySeatMapPortType
     */
    @WebEndpoint(name = "ModifySeatMapEndpointPort")
    public ModifySeatMapPortType getModifySeatMapEndpointPort() {
        return super.getPort(new QName("http://www.hp.com/AirlineSOASchema/ModifySeatMap/", "ModifySeatMapEndpointPort"), ModifySeatMapPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifySeatMapPortType
     */
    @WebEndpoint(name = "ModifySeatMapEndpointPort")
    public ModifySeatMapPortType getModifySeatMapEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.hp.com/AirlineSOASchema/ModifySeatMap/", "ModifySeatMapEndpointPort"), ModifySeatMapPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODIFYSEATMAPSERVICE_EXCEPTION!= null) {
            throw MODIFYSEATMAPSERVICE_EXCEPTION;
        }
        return MODIFYSEATMAPSERVICE_WSDL_LOCATION;
    }

}
